volumes:
  dev_pgdata:

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: odk_publish
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "9062:5432"
    volumes:
      - dev_pgdata:/var/lib/postgresql/data
