services:
  service:
    image: ghcr.io/getodk/central-service:master
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - SYSADMIN_EMAIL=${SYSADMIN_EMAIL}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - NODE_OPTIONS=${SERVICE_NODE_OPTIONS:-}
      - DB_HOST=${DB_HOST:-postgres14}
      - DB_USER=${DB_USER:-odk}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-central}
      - DB_SSL=${DB_SSL:-null}
      - EMAIL_FROM=${EMAIL_FROM:-no-reply@$DOMAIN}
      - EMAIL_HOST=${EMAIL_HOST:-mail}
      - EMAIL_PORT=${EMAIL_PORT:-25}
      - EMAIL_SECURE=${EMAIL_SECURE:-false}
      - EMAIL_IGNORE_TLS=${EMAIL_IGNORE_TLS:-true}
      - EMAIL_USER=${EMAIL_USER:-}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - OIDC_ENABLED=${OIDC_ENABLED:-false}
      - OIDC_ISSUER_URL=${OIDC_ISSUER_URL:-}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:-}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:-}
      - SENTRY_ORG_SUBDOMAIN=${SENTRY_ORG_SUBDOMAIN:-o130137}
      - SENTRY_KEY=${SENTRY_KEY:-3cf75f54983e473da6bd07daddf0d2ee}
      - SENTRY_PROJECT=${SENTRY_PROJECT:-1298632}
      - S3_SERVER=${S3_SERVER:-}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-}
    command:
      ["wait-for-it", "${DB_HOST:-postgres14}:5432", "--", "./start-odk.sh"]
  nginx:
    image: ghcr.io/caktus/central-nginx:v2024.3.1
    depends_on:
      - service
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - CERTBOT_EMAIL=${SYSADMIN_EMAIL}
      - SSL_TYPE=${SSL_TYPE:-letsencrypt}
      - OIDC_ENABLED=${OIDC_ENABLED:-false}
      - SENTRY_ORG_SUBDOMAIN=${SENTRY_ORG_SUBDOMAIN:-o130137}
      - SENTRY_KEY=${SENTRY_KEY:-3cf75f54983e473da6bd07daddf0d2ee}
      - SENTRY_PROJECT=${SENTRY_PROJECT:-1298632}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 80 || exit 1"]
  enketo:
    image: ghcr.io/caktus/central-enketo:v2024.3.1
    volumes:
      - dev_secrets:/etc/secrets
    depends_on:
      - secrets
      - enketo-redis-main
      - enketo-redis-cache
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - SUPPORT_EMAIL=${SYSADMIN_EMAIL}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - SENTRY_ORG_SUBDOMAIN=${SENTRY_ORG_SUBDOMAIN:-o130137}
      - SENTRY_KEY=${SENTRY_KEY:-3cf75f54983e473da6bd07daddf0d2ee}
      - SENTRY_PROJECT=${SENTRY_PROJECT:-1298632}
  enketo-redis-main:
    image: redis:7.2
    volumes:
      - enketo-redis-main:/data
  enketo-redis-cache:
    image: redis:7.2
    volumes:
      - enketo-redis-cache:/data
  secrets:
    image: ghcr.io/caktus/central-secrets:v2024.3.1
    volumes:
      - dev_secrets:/etc/secrets
    working_dir: /etc/secrets
    command: /bin/sh -c 'echo "s0m3v3rys3cr3tk3y" > enketo-secret && echo "this $3cr3t key is crackable" > enketo-less-secret && echo "enketorules" > enketo-api-key'
  pyxform:
    image: "ghcr.io/getodk/pyxform-http:v3.0.0"
volumes:
  dev_secrets:
  enketo-redis-main:
  enketo-redis-cache:
